/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author DELL
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        menuCadHospede = new javax.swing.JMenuItem();
        menuConsHospede = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        menuCadQuartos = new javax.swing.JMenuItem();
        menuConsQuartos = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        menuCadFuncionarios = new javax.swing.JMenuItem();
        menuConsFuncionarios = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        menuCadFornecedores = new javax.swing.JMenuItem();
        menuConsFornecedores = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        menuCadProdutos = new javax.swing.JMenuItem();
        menuConsProdutos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCadReservaReservas = new javax.swing.JMenuItem();
        menuConsReservaReservas = new javax.swing.JMenuItem();
        menuFinalizarReservaReservas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuProdutosVendas = new javax.swing.JMenuItem();
        menuServiçosVendas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        menuCadContasaPagar = new javax.swing.JMenuItem();
        menuConsContasaPagar = new javax.swing.JMenuItem();
        jMenu20 = new javax.swing.JMenu();
        menuCadContasaReceber = new javax.swing.JMenuItem();
        menuConsContasaReceber = new javax.swing.JMenuItem();
        menuBalancoFinanceiro = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        menuContasaPagarFinanceiro = new javax.swing.JMenuItem();
        menuContasaReceberFinanceiro = new javax.swing.JMenuItem();
        menuBalancoFinanceiroRelatorios = new javax.swing.JMenuItem();
        jMenu23 = new javax.swing.JMenu();
        menuQuartosDisponiveisReservas = new javax.swing.JMenuItem();
        menuQuartosOcupadosReservas = new javax.swing.JMenuItem();
        menuReservasFuturasReservas = new javax.swing.JMenuItem();
        jMenu24 = new javax.swing.JMenu();
        menuHospedesRelatorios = new javax.swing.JMenuItem();
        menuFuncionariosRelatorios = new javax.swing.JMenuItem();
        menuFornecedoresRelatorios = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuFazerBackupSeguranca = new javax.swing.JMenuItem();
        menuRestaurarBackupSeguranca = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu30 = new javax.swing.JMenu();
        menuAddImagemTelaDeFundo = new javax.swing.JMenuItem();
        menuRemoverImagemTelaDeFundo = new javax.swing.JMenuItem();
        menuRestaurarPadraoTelaDeFundo = new javax.swing.JMenuItem();
        menuSobreSistemaSeguranca = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastros   |");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu9.setText("Hóspedes");

        menuCadHospede.setText("Cadastrar");
        jMenu9.add(menuCadHospede);

        menuConsHospede.setText("Consultar");
        jMenu9.add(menuConsHospede);

        jMenu1.add(jMenu9);

        jMenu10.setText("Quartos");

        menuCadQuartos.setText("Cadastrar");
        jMenu10.add(menuCadQuartos);

        menuConsQuartos.setText("Consultar");
        jMenu10.add(menuConsQuartos);

        jMenu1.add(jMenu10);

        jMenu11.setText("Funcionários");

        menuCadFuncionarios.setText("Cadastrar");
        jMenu11.add(menuCadFuncionarios);

        menuConsFuncionarios.setText("Consultar");
        jMenu11.add(menuConsFuncionarios);

        jMenu1.add(jMenu11);

        jMenu12.setText("Fornecedores");

        menuCadFornecedores.setText("Cadastrar");
        jMenu12.add(menuCadFornecedores);

        menuConsFornecedores.setText("Consultar");
        jMenu12.add(menuConsFornecedores);

        jMenu1.add(jMenu12);

        jMenu13.setText("Produtos");

        menuCadProdutos.setText("Cadastrar");
        jMenu13.add(menuCadProdutos);

        menuConsProdutos.setText("Consultar");
        jMenu13.add(menuConsProdutos);

        jMenu1.add(jMenu13);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reservas   |");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuCadReservaReservas.setText("Cadastrar Reserva");
        jMenu2.add(menuCadReservaReservas);

        menuConsReservaReservas.setText("Consultar Reserva");
        menuConsReservaReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsReservaReservasActionPerformed(evt);
            }
        });
        jMenu2.add(menuConsReservaReservas);

        menuFinalizarReservaReservas.setText("Finalizar Reserva");
        jMenu2.add(menuFinalizarReservaReservas);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Vendas   |");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuProdutosVendas.setText("Produtos");
        jMenu3.add(menuProdutosVendas);

        menuServiçosVendas.setText("Serviços");
        menuServiçosVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServiçosVendasActionPerformed(evt);
            }
        });
        jMenu3.add(menuServiçosVendas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Financeiro   |");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu19.setText("Contas a Pagar");

        menuCadContasaPagar.setText("Cadastrar");
        jMenu19.add(menuCadContasaPagar);

        menuConsContasaPagar.setText("Consultar");
        jMenu19.add(menuConsContasaPagar);

        jMenu4.add(jMenu19);

        jMenu20.setText("Contas a Receber");

        menuCadContasaReceber.setText("Cadastrar");
        jMenu20.add(menuCadContasaReceber);

        menuConsContasaReceber.setText("Consultar");
        jMenu20.add(menuConsContasaReceber);

        jMenu4.add(jMenu20);

        menuBalancoFinanceiro.setText("Balanço");
        jMenu4.add(menuBalancoFinanceiro);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Relatórios   |");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu22.setText("Financeiro");

        menuContasaPagarFinanceiro.setText("Contas a Pagar");
        jMenu22.add(menuContasaPagarFinanceiro);

        menuContasaReceberFinanceiro.setText("Contas a Receber");
        menuContasaReceberFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContasaReceberFinanceiroActionPerformed(evt);
            }
        });
        jMenu22.add(menuContasaReceberFinanceiro);

        menuBalancoFinanceiroRelatorios.setText("Balanço");
        menuBalancoFinanceiroRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBalancoFinanceiroRelatoriosActionPerformed(evt);
            }
        });
        jMenu22.add(menuBalancoFinanceiroRelatorios);

        jMenu5.add(jMenu22);

        jMenu23.setText("Reservas");

        menuQuartosDisponiveisReservas.setText("Quartos Disponíveis");
        menuQuartosDisponiveisReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuartosDisponiveisReservasActionPerformed(evt);
            }
        });
        jMenu23.add(menuQuartosDisponiveisReservas);

        menuQuartosOcupadosReservas.setText("Quartos Ocupados");
        jMenu23.add(menuQuartosOcupadosReservas);

        menuReservasFuturasReservas.setText("Reservas Futuras");
        menuReservasFuturasReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReservasFuturasReservasActionPerformed(evt);
            }
        });
        jMenu23.add(menuReservasFuturasReservas);

        jMenu5.add(jMenu23);

        jMenu24.setText("Vendas");
        jMenu5.add(jMenu24);

        menuHospedesRelatorios.setText("Hóspedes");
        jMenu5.add(menuHospedesRelatorios);

        menuFuncionariosRelatorios.setText("Funcionários");
        menuFuncionariosRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionariosRelatoriosActionPerformed(evt);
            }
        });
        jMenu5.add(menuFuncionariosRelatorios);

        menuFornecedoresRelatorios.setText("Fornecedores");
        jMenu5.add(menuFornecedoresRelatorios);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Segurança   |");
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuFazerBackupSeguranca.setText("Fazer Backup");
        menuFazerBackupSeguranca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFazerBackupSegurancaActionPerformed(evt);
            }
        });
        jMenu6.add(menuFazerBackupSeguranca);

        menuRestaurarBackupSeguranca.setText("Restaurar Backup");
        jMenu6.add(menuRestaurarBackupSeguranca);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Ferramentas   |");
        jMenu7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu30.setText("Tela de Fundo");

        menuAddImagemTelaDeFundo.setText("Add imagem");
        jMenu30.add(menuAddImagemTelaDeFundo);

        menuRemoverImagemTelaDeFundo.setText("Remover imagem");
        jMenu30.add(menuRemoverImagemTelaDeFundo);

        menuRestaurarPadraoTelaDeFundo.setText("Restaurar padrão");
        jMenu30.add(menuRestaurarPadraoTelaDeFundo);

        jMenu7.add(jMenu30);

        menuSobreSistemaSeguranca.setText("Sobre o Sistema");
        jMenu7.add(menuSobreSistemaSeguranca);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Sair");
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuConsReservaReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsReservaReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuConsReservaReservasActionPerformed

    private void menuServiçosVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServiçosVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuServiçosVendasActionPerformed

    private void menuReservasFuturasReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReservasFuturasReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuReservasFuturasReservasActionPerformed

    private void menuQuartosDisponiveisReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuartosDisponiveisReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuQuartosDisponiveisReservasActionPerformed

    private void menuBalancoFinanceiroRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBalancoFinanceiroRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBalancoFinanceiroRelatoriosActionPerformed

    private void menuContasaReceberFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContasaReceberFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuContasaReceberFinanceiroActionPerformed

    private void menuFuncionariosRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionariosRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFuncionariosRelatoriosActionPerformed

    private void menuFazerBackupSegurancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFazerBackupSegurancaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFazerBackupSegurancaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAddImagemTelaDeFundo;
    private javax.swing.JMenuItem menuBalancoFinanceiro;
    private javax.swing.JMenuItem menuBalancoFinanceiroRelatorios;
    private javax.swing.JMenuItem menuCadContasaPagar;
    private javax.swing.JMenuItem menuCadContasaReceber;
    private javax.swing.JMenuItem menuCadFornecedores;
    private javax.swing.JMenuItem menuCadFuncionarios;
    private javax.swing.JMenuItem menuCadHospede;
    private javax.swing.JMenuItem menuCadProdutos;
    private javax.swing.JMenuItem menuCadQuartos;
    private javax.swing.JMenuItem menuCadReservaReservas;
    private javax.swing.JMenuItem menuConsContasaPagar;
    private javax.swing.JMenuItem menuConsContasaReceber;
    private javax.swing.JMenuItem menuConsFornecedores;
    private javax.swing.JMenuItem menuConsFuncionarios;
    private javax.swing.JMenuItem menuConsHospede;
    private javax.swing.JMenuItem menuConsProdutos;
    private javax.swing.JMenuItem menuConsQuartos;
    private javax.swing.JMenuItem menuConsReservaReservas;
    private javax.swing.JMenuItem menuContasaPagarFinanceiro;
    private javax.swing.JMenuItem menuContasaReceberFinanceiro;
    private javax.swing.JMenuItem menuFazerBackupSeguranca;
    private javax.swing.JMenuItem menuFinalizarReservaReservas;
    private javax.swing.JMenuItem menuFornecedoresRelatorios;
    private javax.swing.JMenuItem menuFuncionariosRelatorios;
    private javax.swing.JMenuItem menuHospedesRelatorios;
    private javax.swing.JMenuItem menuProdutosVendas;
    private javax.swing.JMenuItem menuQuartosDisponiveisReservas;
    private javax.swing.JMenuItem menuQuartosOcupadosReservas;
    private javax.swing.JMenuItem menuRemoverImagemTelaDeFundo;
    private javax.swing.JMenuItem menuReservasFuturasReservas;
    private javax.swing.JMenuItem menuRestaurarBackupSeguranca;
    private javax.swing.JMenuItem menuRestaurarPadraoTelaDeFundo;
    private javax.swing.JMenuItem menuServiçosVendas;
    private javax.swing.JMenuItem menuSobreSistemaSeguranca;
    // End of variables declaration//GEN-END:variables
}
